spring:
  datasource:
    datasource:
    url: jdbc:mariadb://localhost:3306/fintech
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  application:
    name: Fintech
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    secret: eW91bmdzaWstc3ByaW5nLWJvb3Qtc3RvcmV0YWJsZXJlc2VydmF0aW9uc2VydmljZS1wcm9qZWN0LXR1dG9yaWFsLWp3dC1zZWNyZXQta2V5Cg==
